"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.1
  - malware: 1.0.1
  - reports: 1.0.4
  - sources: 1.0.3
  - actors: 1.0.2
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from verity471.models.get_watcher_group_response_wrapper import GetWatcherGroupResponseWrapper
from verity471.models.get_watcher_response_wrapper import GetWatcherResponseWrapper
from verity471.models.watcher_group_type import WatcherGroupType

from verity471.api_client import ApiClient, RequestSerialized
from verity471.api_response import ApiResponse
from verity471.rest import RESTResponseType


class WatchersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_watcher_groups(
        self,
        watcher_group_id: Annotated[Optional[StrictInt], Field(description="Enables returning only watchers for specific group")] = None,
        watcher_group_type: Annotated[Optional[WatcherGroupType], Field(description="Enables filtering by group type")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Filter results based on watcher group name")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetWatcherGroupResponseWrapper:
        """Get list of watcher groups for user


        :param watcher_group_id: Enables returning only watchers for specific group
        :type watcher_group_id: int
        :param watcher_group_type: Enables filtering by group type
        :type watcher_group_type: WatcherGroupType
        :param name: Filter results based on watcher group name
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_watcher_groups_serialize(
            watcher_group_id=watcher_group_id,
            watcher_group_type=watcher_group_type,
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetWatcherGroupResponseWrapper",
            '400': "BadRequest",
            '401': "Unauthorized",
            '403': "Forbidden",
            '404': "NotFound",
            '409': "Conflict",
            '500': "InternalServerError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_watcher_groups_with_http_info(
        self,
        watcher_group_id: Annotated[Optional[StrictInt], Field(description="Enables returning only watchers for specific group")] = None,
        watcher_group_type: Annotated[Optional[WatcherGroupType], Field(description="Enables filtering by group type")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Filter results based on watcher group name")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetWatcherGroupResponseWrapper]:
        """Get list of watcher groups for user


        :param watcher_group_id: Enables returning only watchers for specific group
        :type watcher_group_id: int
        :param watcher_group_type: Enables filtering by group type
        :type watcher_group_type: WatcherGroupType
        :param name: Filter results based on watcher group name
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_watcher_groups_serialize(
            watcher_group_id=watcher_group_id,
            watcher_group_type=watcher_group_type,
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetWatcherGroupResponseWrapper",
            '400': "BadRequest",
            '401': "Unauthorized",
            '403': "Forbidden",
            '404': "NotFound",
            '409': "Conflict",
            '500': "InternalServerError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_watcher_groups_without_preload_content(
        self,
        watcher_group_id: Annotated[Optional[StrictInt], Field(description="Enables returning only watchers for specific group")] = None,
        watcher_group_type: Annotated[Optional[WatcherGroupType], Field(description="Enables filtering by group type")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Filter results based on watcher group name")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get list of watcher groups for user


        :param watcher_group_id: Enables returning only watchers for specific group
        :type watcher_group_id: int
        :param watcher_group_type: Enables filtering by group type
        :type watcher_group_type: WatcherGroupType
        :param name: Filter results based on watcher group name
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_watcher_groups_serialize(
            watcher_group_id=watcher_group_id,
            watcher_group_type=watcher_group_type,
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetWatcherGroupResponseWrapper",
            '400': "BadRequest",
            '401': "Unauthorized",
            '403': "Forbidden",
            '404': "NotFound",
            '409': "Conflict",
            '500': "InternalServerError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_watcher_groups_serialize(
        self,
        watcher_group_id,
        watcher_group_type,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if watcher_group_id is not None:
            
            _query_params.append(('watcher_group_id', watcher_group_id))
            
        if watcher_group_type is not None:
            
            _query_params.append(('watcher_group_type', watcher_group_type.value))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/watchers/v1/watcher-groups',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_watchers(
        self,
        watcher_id: Annotated[Optional[StrictInt], Field(description="Enables returning only specific watcher")] = None,
        watcher_group_id: Annotated[Optional[StrictInt], Field(description="Enables returning only watchers for specific group")] = None,
        dsl_query: Annotated[Optional[StrictStr], Field(description="Enables returning watchers with specific DSL query")] = None,
        watcher_group_type: Annotated[Optional[WatcherGroupType], Field(description="Enables filtering by group type")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Filter results based on watcher name")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetWatcherResponseWrapper:
        """Get list of watchers for the current user


        :param watcher_id: Enables returning only specific watcher
        :type watcher_id: int
        :param watcher_group_id: Enables returning only watchers for specific group
        :type watcher_group_id: int
        :param dsl_query: Enables returning watchers with specific DSL query
        :type dsl_query: str
        :param watcher_group_type: Enables filtering by group type
        :type watcher_group_type: WatcherGroupType
        :param name: Filter results based on watcher name
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_watchers_serialize(
            watcher_id=watcher_id,
            watcher_group_id=watcher_group_id,
            dsl_query=dsl_query,
            watcher_group_type=watcher_group_type,
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetWatcherResponseWrapper",
            '400': "BadRequest",
            '401': "Unauthorized",
            '403': "Forbidden",
            '404': "NotFound",
            '409': "Conflict",
            '500': "InternalServerError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_watchers_with_http_info(
        self,
        watcher_id: Annotated[Optional[StrictInt], Field(description="Enables returning only specific watcher")] = None,
        watcher_group_id: Annotated[Optional[StrictInt], Field(description="Enables returning only watchers for specific group")] = None,
        dsl_query: Annotated[Optional[StrictStr], Field(description="Enables returning watchers with specific DSL query")] = None,
        watcher_group_type: Annotated[Optional[WatcherGroupType], Field(description="Enables filtering by group type")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Filter results based on watcher name")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetWatcherResponseWrapper]:
        """Get list of watchers for the current user


        :param watcher_id: Enables returning only specific watcher
        :type watcher_id: int
        :param watcher_group_id: Enables returning only watchers for specific group
        :type watcher_group_id: int
        :param dsl_query: Enables returning watchers with specific DSL query
        :type dsl_query: str
        :param watcher_group_type: Enables filtering by group type
        :type watcher_group_type: WatcherGroupType
        :param name: Filter results based on watcher name
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_watchers_serialize(
            watcher_id=watcher_id,
            watcher_group_id=watcher_group_id,
            dsl_query=dsl_query,
            watcher_group_type=watcher_group_type,
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetWatcherResponseWrapper",
            '400': "BadRequest",
            '401': "Unauthorized",
            '403': "Forbidden",
            '404': "NotFound",
            '409': "Conflict",
            '500': "InternalServerError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_watchers_without_preload_content(
        self,
        watcher_id: Annotated[Optional[StrictInt], Field(description="Enables returning only specific watcher")] = None,
        watcher_group_id: Annotated[Optional[StrictInt], Field(description="Enables returning only watchers for specific group")] = None,
        dsl_query: Annotated[Optional[StrictStr], Field(description="Enables returning watchers with specific DSL query")] = None,
        watcher_group_type: Annotated[Optional[WatcherGroupType], Field(description="Enables filtering by group type")] = None,
        name: Annotated[Optional[StrictStr], Field(description="Filter results based on watcher name")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get list of watchers for the current user


        :param watcher_id: Enables returning only specific watcher
        :type watcher_id: int
        :param watcher_group_id: Enables returning only watchers for specific group
        :type watcher_group_id: int
        :param dsl_query: Enables returning watchers with specific DSL query
        :type dsl_query: str
        :param watcher_group_type: Enables filtering by group type
        :type watcher_group_type: WatcherGroupType
        :param name: Filter results based on watcher name
        :type name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_watchers_serialize(
            watcher_id=watcher_id,
            watcher_group_id=watcher_group_id,
            dsl_query=dsl_query,
            watcher_group_type=watcher_group_type,
            name=name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetWatcherResponseWrapper",
            '400': "BadRequest",
            '401': "Unauthorized",
            '403': "Forbidden",
            '404': "NotFound",
            '409': "Conflict",
            '500': "InternalServerError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_watchers_serialize(
        self,
        watcher_id,
        watcher_group_id,
        dsl_query,
        watcher_group_type,
        name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if watcher_id is not None:
            
            _query_params.append(('watcher_id', watcher_id))
            
        if watcher_group_id is not None:
            
            _query_params.append(('watcher_group_id', watcher_group_id))
            
        if dsl_query is not None:
            
            _query_params.append(('dsl_query', dsl_query))
            
        if watcher_group_type is not None:
            
            _query_params.append(('watcher_group_type', watcher_group_type.value))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'basicAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/integrations/watchers/v1/watchers',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


