# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0
  - indicators: 1.0.0
  - malware: 1.0.0
  - reports: 1.0.0
  - sources: 1.0.1
  - actors: 1.0.0
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.cred_credential_set_response import CredCredentialSetResponse
from verity471.models.credential_occurrence_cred_response import CredentialOccurrenceCredResponse
from verity471.models.info_stealer_response_option import InfoStealerResponseOption
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class CredentialOccurrenceDataResponse(BaseModel):
    """
    Credential occurrence with related objects.
    """ # noqa: E501
    file_path: Optional[StrictStr] = Field(default=None, description="Credential occurrence file path.")
    accessed_url: Optional[StrictStr] = Field(default=None, description="Accessed URL.")
    credential: Optional[CredentialOccurrenceCredResponse] = None
    credential_set: Optional[CredCredentialSetResponse] = None
    info_stealer: InfoStealerResponseOption
    software_name: Optional[StrictStr] = Field(default=None, description="Name of the software.")
    credential_type: Optional[StrictStr] = Field(default=None, description="Type of the credential set this credential belongs to.")
    __properties: ClassVar[List[str]] = ["file_path", "accessed_url", "credential", "credential_set", "info_stealer", "software_name", "credential_type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CredentialOccurrenceDataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of credential
        if self.credential:
            _dict['credential'] = self.credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credential_set
        if self.credential_set:
            _dict['credential_set'] = self.credential_set.to_dict()
        # override the default output from pydantic by calling `to_dict()` of info_stealer
        if self.info_stealer:
            _dict['info_stealer'] = self.info_stealer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CredentialOccurrenceDataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file_path": obj.get("file_path"),
            "accessed_url": obj.get("accessed_url"),
            "credential": CredentialOccurrenceCredResponse.from_dict(obj["credential"]) if obj.get("credential") is not None else None,
            "credential_set": CredCredentialSetResponse.from_dict(obj["credential_set"]) if obj.get("credential_set") is not None else None,
            "info_stealer": InfoStealerResponseOption.from_dict(obj["info_stealer"]) if obj.get("info_stealer") is not None else None,
            "software_name": obj.get("software_name"),
            "credential_type": obj.get("credential_type")
        })
        return _obj


