# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.1
  - malware: 1.0.1
  - reports: 1.0.1
  - sources: 1.0.3
  - actors: 1.0.2
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class CredPasswordComplexityResponse(BaseModel):
    """
    Details of the password's complexity.
    """ # noqa: E501
    lowercase: Optional[StrictInt] = Field(default=None, description="The number of lowercase letters in the password.")
    uppercase: Optional[StrictInt] = Field(default=None, description="The number of uppercase letters in the password.")
    numbers: Optional[StrictInt] = Field(default=None, description="The number of digits in the password.")
    symbols: Optional[StrictInt] = Field(default=None, description="The number of symbols in the password.")
    punctuation_marks: Optional[StrictInt] = Field(default=None, description="The number of punctuation marks in the password.")
    separators: Optional[StrictInt] = Field(default=None, description="The number of separators in the password.")
    other: Optional[StrictInt] = Field(default=None, description="The number of other characters in the password.")
    length: Optional[StrictInt] = Field(default=None, description="The length of the password.")
    score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The password score.")
    weakness: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The password weakness.")
    entropy: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The password entropy.")
    __properties: ClassVar[List[str]] = ["lowercase", "uppercase", "numbers", "symbols", "punctuation_marks", "separators", "other", "length", "score", "weakness", "entropy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CredPasswordComplexityResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CredPasswordComplexityResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lowercase": obj.get("lowercase"),
            "uppercase": obj.get("uppercase"),
            "numbers": obj.get("numbers"),
            "symbols": obj.get("symbols"),
            "punctuation_marks": obj.get("punctuation_marks"),
            "separators": obj.get("separators"),
            "other": obj.get("other"),
            "length": obj.get("length"),
            "score": obj.get("score"),
            "weakness": obj.get("weakness"),
            "entropy": obj.get("entropy")
        })
        return _obj


