# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.4
  - indicators: 1.0.1
  - malware: 1.0.1
  - reports: 1.0.5
  - sources: 1.0.5
  - actors: 1.0.2
  - watchers: 1.0.1
  - observables: 1.0.1
  - entities: 1.0.1
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.11
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.activity import Activity
from verity471.models.attachment_data import AttachmentData
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class DataLeakSitePost(BaseModel):
    """
    DataLeakSitePost
    """ # noqa: E501
    activity: Activity
    attachment_data: Dict[str, AttachmentData]
    created_at: Optional[StrictStr] = None
    id: StrictStr
    inactive_since: Optional[StrictStr] = None
    is_inactive: Optional[StrictBool] = None
    message: StrictStr
    published_at: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    title: StrictStr
    __properties: ClassVar[List[str]] = ["activity", "attachment_data", "created_at", "id", "inactive_since", "is_inactive", "message", "published_at", "source_url", "title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataLeakSitePost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of activity
        if self.activity:
            _dict['activity'] = self.activity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in attachment_data (dict)
        _field_dict = {}
        if self.attachment_data:
            for _key_attachment_data in self.attachment_data:
                if self.attachment_data[_key_attachment_data]:
                    _field_dict[_key_attachment_data] = self.attachment_data[_key_attachment_data].to_dict()
            _dict['attachment_data'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataLeakSitePost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "activity": Activity.from_dict(obj["activity"]) if obj.get("activity") is not None else None,
            "attachment_data": dict(
                (_k, AttachmentData.from_dict(_v))
                for _k, _v in obj["attachment_data"].items()
            )
            if obj.get("attachment_data") is not None
            else None,
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "inactive_since": obj.get("inactive_since"),
            "is_inactive": obj.get("is_inactive"),
            "message": obj.get("message"),
            "published_at": obj.get("published_at"),
            "source_url": obj.get("source_url"),
            "title": obj.get("title")
        })
        return _obj


