# coding: utf-8

"""
    Verity API

      - credentials-api: 1.0 (sha256: d9388712b26f2f02d99e51575068a820a5e715140740ea69c07486826c2821c0)   - girs-api: 1.0 (sha256: 070d8920e035f2efab0de4a0debbfb8b0d4943d8651484e13f940b4ec6a5d785)   - indicators-api: 1.0 (sha256: af005f41eca833b6369675f267fe53b4eb81c0b0f2f3804cb7891547a3baadd7)   - malware-api: 1.0 (sha256: 968014f426d5cf3e8b8b16464f10b5005f603d6f6737db12219f3b2e1eb27787)   - reports-api: 1.0 (sha256: 2820a8e62bd056e925df05f7aaf7037d0468c69185023d9090295ad611e1c231)   - sources-api: 1.0 (sha256: 77392c136168b69e52a93036fe2b2d77d2c6b97900698b45b27cecd8a93356de) 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from verity471.verity_stix import STIXMapperSettings
from verity471.verity_stix.mappers.common import StixMapper

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DataLeakSitePostFileListing(BaseModel):
    """
    Post file listing
    """ # noqa: E501
    download_url: Optional[StrictStr] = Field(default=None, description="API url for download file listing")
    __properties: ClassVar[List[str]] = ["download_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: STIXMapperSettings = None):
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataLeakSitePostFileListing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataLeakSitePostFileListing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "download_url": obj.get("download_url")
        })
        return _obj


