# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.0
  - malware: 1.0.0
  - reports: 1.0.0
  - sources: 1.0.2
  - actors: 1.0.1
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FintelReportSubType(str, Enum):
    """
    Fintel report subtype, e.g. ACTOR_PROFILE
    """

    """
    allowed enum values
    """
    ACTOR_PROFILE = 'actor_profile'
    INTELLIGENCE_BULLETIN = 'intelligence_bulletin'
    SERVICE_PROFILE = 'service_profile'
    UNDERGROUND_PERSPECTIVE = 'underground_perspective'
    UNDERGROUND_PULSE = 'underground_pulse'
    WHITEPAPER = 'whitepaper'
    THREAT_BRIEF = 'threat_brief'
    BREACH_REPORT = 'breach_report'
    INTELLIGENCE_SUMMARY = 'intelligence_summary'
    MALWARE_CAMPAIGN = 'malware_campaign'
    FINTEL_BLOG = 'fintel_blog'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FintelReportSubType from a JSON string"""
        return cls(json.loads(json_str))


