# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.0
  - malware: 1.0.0
  - reports: 1.0.0
  - sources: 1.0.2
  - actors: 1.0.1
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GeopolReportSubType(str, Enum):
    """
    Report subtype, e.g. intelligence_bulletin
    """

    """
    allowed enum values
    """
    SPOT_REPORT = 'spot_report'
    INTELLIGENCE_BULLETIN = 'intelligence_bulletin'
    INTELLIGENCE_SUMMARY = 'intelligence_summary'
    TENSION_POINT_PROFILE = 'tension_point_profile'
    THREAT_BRIEF = 'threat_brief'
    SIGNIFICANT_ACTIVITY_REPORT = 'significant_activity_report'
    INTELLIGENCE_ESTIMATE = 'intelligence_estimate'
    ADVERSARY_PROFILE = 'adversary_profile'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeopolReportSubType from a JSON string"""
        return cls(json.loads(json_str))


