# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.1
  - malware: 1.0.1
  - reports: 1.0.3
  - sources: 1.0.3
  - actors: 1.0.2
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.notification_settings_response import NotificationSettingsResponse
from verity471.models.share_settings_response import ShareSettingsResponse
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class GetWatcherGroupResponse(BaseModel):
    """
    GetWatcherGroupResponse
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    description: StrictStr
    created_by: StrictStr
    owner_user_id: StrictStr
    organisation_id: StrictStr
    watcher_ids: Optional[List[StrictInt]] = None
    is_editable: StrictBool
    is_global: StrictBool
    is_subscribed: StrictBool
    is_muted: StrictBool
    notification_settings: Optional[List[NotificationSettingsResponse]] = None
    sharing_settings: Optional[List[ShareSettingsResponse]] = None
    updated_by: Optional[StrictStr] = None
    creation_ts: datetime
    last_updated_ts: datetime
    __properties: ClassVar[List[str]] = ["id", "name", "description", "created_by", "owner_user_id", "organisation_id", "watcher_ids", "is_editable", "is_global", "is_subscribed", "is_muted", "notification_settings", "sharing_settings", "updated_by", "creation_ts", "last_updated_ts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetWatcherGroupResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in notification_settings (list)
        _items = []
        if self.notification_settings:
            for _item_notification_settings in self.notification_settings:
                if _item_notification_settings:
                    _items.append(_item_notification_settings.to_dict())
            _dict['notification_settings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sharing_settings (list)
        _items = []
        if self.sharing_settings:
            for _item_sharing_settings in self.sharing_settings:
                if _item_sharing_settings:
                    _items.append(_item_sharing_settings.to_dict())
            _dict['sharing_settings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetWatcherGroupResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "created_by": obj.get("created_by"),
            "owner_user_id": obj.get("owner_user_id"),
            "organisation_id": obj.get("organisation_id"),
            "watcher_ids": obj.get("watcher_ids"),
            "is_editable": obj.get("is_editable"),
            "is_global": obj.get("is_global"),
            "is_subscribed": obj.get("is_subscribed"),
            "is_muted": obj.get("is_muted"),
            "notification_settings": [NotificationSettingsResponse.from_dict(_item) for _item in obj["notification_settings"]] if obj.get("notification_settings") is not None else None,
            "sharing_settings": [ShareSettingsResponse.from_dict(_item) for _item in obj["sharing_settings"]] if obj.get("sharing_settings") is not None else None,
            "updated_by": obj.get("updated_by"),
            "creation_ts": obj.get("creation_ts"),
            "last_updated_ts": obj.get("last_updated_ts")
        })
        return _obj


