# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0
  - indicators: 1.0.0
  - malware: 1.0.0
  - reports: 1.0.0
  - sources: 1.0.1
  - actors: 1.0.0
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class InfoStealerResponseSet(BaseModel):
    """
    Array of malware family objects.
    """ # noqa: E501
    malware_family: Optional[List[StrictStr]] = Field(default=None, description="Malware family name.")
    malware_install_path: Optional[List[StrictStr]] = Field(default=None, description="Malware installation path.")
    screenshot_path: Optional[List[StrictStr]] = Field(default=None, description="Screenshot path.")
    infection_ts: Optional[List[StrictStr]] = Field(default=None, description="Date of infection.")
    machine_id: Optional[List[StrictStr]] = Field(default=None, description="Id of the machine.")
    pc_name: Optional[List[StrictStr]] = Field(default=None, description="Name of the machine.")
    computer_username: Optional[List[StrictStr]] = Field(default=None, description="Name of the user account.")
    ip: Optional[List[StrictStr]] = Field(default=None, description="IP address.")
    os: Optional[List[StrictStr]] = Field(default=None, description="Operating system.")
    antivirus_software: Optional[List[StrictStr]] = Field(default=None, description="Antivirus software.")
    isp: Optional[List[StrictStr]] = Field(default=None, description="Internet Service Provider.")
    version: Optional[List[StrictStr]] = Field(default=None, description="Version.")
    __properties: ClassVar[List[str]] = ["malware_family", "malware_install_path", "screenshot_path", "infection_ts", "machine_id", "pc_name", "computer_username", "ip", "os", "antivirus_software", "isp", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InfoStealerResponseSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InfoStealerResponseSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "malware_family": obj.get("malware_family"),
            "malware_install_path": obj.get("malware_install_path"),
            "screenshot_path": obj.get("screenshot_path"),
            "infection_ts": obj.get("infection_ts"),
            "machine_id": obj.get("machine_id"),
            "pc_name": obj.get("pc_name"),
            "computer_username": obj.get("computer_username"),
            "ip": obj.get("ip"),
            "os": obj.get("os"),
            "antivirus_software": obj.get("antivirus_software"),
            "isp": obj.get("isp"),
            "version": obj.get("version")
        })
        return _obj


