# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.1
  - malware: 1.0.1
  - reports: 1.0.4
  - sources: 1.0.3
  - actors: 1.0.2
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InterestLevel(str, Enum):
    """
    InterestLevel
    """

    """
    allowed enum values
    """
    DISCLOSED_PUBLICLY = 'disclosed_publicly'
    EXPLOIT_SOUGHT = 'exploit_sought'
    RESEARCHED_PUBLICLY = 'researched_publicly'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InterestLevel from a JSON string"""
        return cls(json.loads(json_str))


