# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0
  - indicators: 1.0.0
  - malware: 1.0.0
  - reports: 1.0.0
  - sources: 1.0.1
  - actors: 1.0.0
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.translation_status import TranslationStatus
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class PrivateMessageResponse1(BaseModel):
    """
    PrivateMessageResponse1
    """ # noqa: E501
    conversation_id: Optional[StrictStr] = Field(default=None, description="Conversation id")
    creation_ts: StrictStr = Field(description="Publish date in ISO 8601 format")
    id: StrictStr = Field(description="Unique id of private message")
    message: StrictStr = Field(description="Original Message")
    subject: Optional[StrictStr] = Field(default=None, description="Message subject")
    translated_message: Optional[StrictStr] = Field(default=None, description="Contains translated message if available")
    translated_subject: Optional[StrictStr] = Field(default=None, description="Contains translated message subject if available")
    translation_status: Optional[TranslationStatus] = None
    __properties: ClassVar[List[str]] = ["conversation_id", "creation_ts", "id", "message", "subject", "translated_message", "translated_subject", "translation_status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrivateMessageResponse1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrivateMessageResponse1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversation_id": obj.get("conversation_id"),
            "creation_ts": obj.get("creation_ts"),
            "id": obj.get("id"),
            "message": obj.get("message"),
            "subject": obj.get("subject"),
            "translated_message": obj.get("translated_message"),
            "translated_subject": obj.get("translated_subject"),
            "translation_status": obj.get("translation_status")
        })
        return _obj


