# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0 (sha256: a6a51890d140b2280d6700ac6e108afa62dfb55bc79aa73b386946c7fa1e691f)
  - girs: 1.0.0 (sha256: f9f8228e2e27b95ba259939a46eda91618b96d6be76bbcba7db47dabb9515cdb)
  - indicators: 1.0.0 (sha256: 039a97ee798c2d28608d8b35f4eaa224b15c8a183a36cf2600321314f75f4777)
  - malware: 1.0.0 (sha256: 41c96d01c01cc5c93820e5dda691e8d0df53e28da1af8ccc84a233b29745fb11)
  - reports: 1.0.0 (sha256: 2050ae4d25813cd47834ae3843040a8d96723284b4b4ee4d2e4818a360a6aca7)
  - sources: 1.0.0 (sha256: a293621b477b279e532bde19e03f25becd2d7fb553b2b270d4e874ba206b823a)


    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from verity471.verity_stix import STIXMapperSettings
from verity471.verity_stix.mappers.common import StixMapper

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.author_actor1 import AuthorActor1
from verity471.models.forums_response1 import ForumsResponse1
from verity471.models.private_message_response1 import PrivateMessageResponse1
from typing import Optional, Set
from typing_extensions import Self

class PrivateMessageDetails1(BaseModel):
    """
    PrivateMessageDetails1
    """ # noqa: E501
    author: Optional[AuthorActor1] = None
    forum: Optional[ForumsResponse1] = None
    private_message: PrivateMessageResponse1
    recipient: Optional[AuthorActor1] = None
    __properties: ClassVar[List[str]] = ["author", "forum", "private_message", "recipient"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: STIXMapperSettings = None):
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrivateMessageDetails1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of forum
        if self.forum:
            _dict['forum'] = self.forum.to_dict()
        # override the default output from pydantic by calling `to_dict()` of private_message
        if self.private_message:
            _dict['private_message'] = self.private_message.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recipient
        if self.recipient:
            _dict['recipient'] = self.recipient.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrivateMessageDetails1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "author": AuthorActor1.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "forum": ForumsResponse1.from_dict(obj["forum"]) if obj.get("forum") is not None else None,
            "private_message": PrivateMessageResponse1.from_dict(obj["private_message"]) if obj.get("private_message") is not None else None,
            "recipient": AuthorActor1.from_dict(obj["recipient"]) if obj.get("recipient") is not None else None
        })
        return _obj


