# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0 (sha256: a6a51890d140b2280d6700ac6e108afa62dfb55bc79aa73b386946c7fa1e691f)
  - girs: 1.0.0 (sha256: f9f8228e2e27b95ba259939a46eda91618b96d6be76bbcba7db47dabb9515cdb)
  - indicators: 1.0.0 (sha256: 039a97ee798c2d28608d8b35f4eaa224b15c8a183a36cf2600321314f75f4777)
  - malware: 1.0.0 (sha256: 41c96d01c01cc5c93820e5dda691e8d0df53e28da1af8ccc84a233b29745fb11)
  - reports: 1.0.0 (sha256: 2050ae4d25813cd47834ae3843040a8d96723284b4b4ee4d2e4818a360a6aca7)
  - sources: 1.0.0 (sha256: a293621b477b279e532bde19e03f25becd2d7fb553b2b270d4e874ba206b823a)


    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.assessment import Assessment
from verity471.models.classification import Classification
from verity471.models.links import Links
from verity471.models.report_type import ReportType
from verity471.models.sources_response import SourcesResponse
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class ReportContent(BaseModel):
    """
    Minimal schema for report response with keys, types, and descriptions
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the related report")
    type: ReportType
    sub_type: Optional[StrictStr] = Field(default=None, description="Fintel or Geopol report subtype, e.g. ACTOR_PROFILE")
    title: StrictStr = Field(description="Title of the related report")
    creation_ts: StrictStr = Field(description="Timestamp when the report was published first time")
    released_ts: StrictStr = Field(description="Timestamp when the report was published last time")
    last_updated_ts: StrictStr = Field(description="Timestamp of last report update")
    information_ts: Optional[StrictStr] = Field(default=None, description="Timestamp of the information contained in the report")
    sources: Optional[List[SourcesResponse]] = Field(default=None, description="List of sources referenced in the report")
    classification: Classification
    assessment: Optional[Assessment] = None
    summary: Optional[StrictStr] = Field(default=None, description="Report summary")
    links: Links
    __properties: ClassVar[List[str]] = ["id", "type", "sub_type", "title", "creation_ts", "released_ts", "last_updated_ts", "information_ts", "sources", "classification", "assessment", "summary", "links"]

    @field_validator('sub_type')
    def sub_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['fintel_blog', 'adversary_profile', 'threat_brief', 'intelligence_summary', 'malware_campaign', 'spot_report', 'underground_pulse', 'breach_report', 'actor_profile', 'service_profile', 'whitepaper', 'underground_perspective', 'tension_point_profile', 'intelligence_bulletin', 'intelligence_estimate', 'significant_activity_report']):
            raise ValueError("must be one of enum values ('fintel_blog', 'adversary_profile', 'threat_brief', 'intelligence_summary', 'malware_campaign', 'spot_report', 'underground_pulse', 'breach_report', 'actor_profile', 'service_profile', 'whitepaper', 'underground_perspective', 'tension_point_profile', 'intelligence_bulletin', 'intelligence_estimate', 'significant_activity_report')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item_sources in self.sources:
                if _item_sources:
                    _items.append(_item_sources.to_dict())
            _dict['sources'] = _items
        # override the default output from pydantic by calling `to_dict()` of classification
        if self.classification:
            _dict['classification'] = self.classification.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assessment
        if self.assessment:
            _dict['assessment'] = self.assessment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "sub_type": obj.get("sub_type"),
            "title": obj.get("title"),
            "creation_ts": obj.get("creation_ts"),
            "released_ts": obj.get("released_ts"),
            "last_updated_ts": obj.get("last_updated_ts"),
            "information_ts": obj.get("information_ts"),
            "sources": [SourcesResponse.from_dict(_item) for _item in obj["sources"]] if obj.get("sources") is not None else None,
            "classification": Classification.from_dict(obj["classification"]) if obj.get("classification") is not None else None,
            "assessment": Assessment.from_dict(obj["assessment"]) if obj.get("assessment") is not None else None,
            "summary": obj.get("summary"),
            "links": Links.from_dict(obj["links"]) if obj.get("links") is not None else None
        })
        return _obj


