# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.0
  - malware: 1.0.1
  - reports: 1.0.1
  - sources: 1.0.3
  - actors: 1.0.2
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.links_entities import LinksEntities
from verity471.models.report_type import ReportType
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class ReportEntities(BaseModel):
    """
    ReportEntities
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier of the report")
    type: ReportType
    sub_type: Optional[StrictStr] = Field(default=None, description="Fintel or Geopol report subtype")
    creation_ts: datetime = Field(description="Timestamp when the report was created (ISO 8601)")
    last_updated_ts: datetime = Field(description="Timestamp when the report was last updated (ISO 8601)")
    information_ts: datetime = Field(description="Timestamp of the information in the report (ISO 8601)")
    released_ts: datetime = Field(description="Timestamp when the report was released (ISO 8601)")
    links: LinksEntities
    __properties: ClassVar[List[str]] = ["id", "type", "sub_type", "creation_ts", "last_updated_ts", "information_ts", "released_ts", "links"]

    @field_validator('sub_type')
    def sub_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['fintel_blog', 'adversary_profile', 'threat_brief', 'intelligence_summary', 'malware_campaign', 'spot_report', 'underground_pulse', 'breach_report', 'actor_profile', 'service_profile', 'whitepaper', 'underground_perspective', 'tension_point_profile', 'intelligence_bulletin', 'intelligence_estimate', 'significant_activity_report']):
            raise ValueError("must be one of enum values ('fintel_blog', 'adversary_profile', 'threat_brief', 'intelligence_summary', 'malware_campaign', 'spot_report', 'underground_pulse', 'breach_report', 'actor_profile', 'service_profile', 'whitepaper', 'underground_perspective', 'tension_point_profile', 'intelligence_bulletin', 'intelligence_estimate', 'significant_activity_report')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportEntities from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportEntities from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "sub_type": obj.get("sub_type"),
            "creation_ts": obj.get("creation_ts"),
            "last_updated_ts": obj.get("last_updated_ts"),
            "information_ts": obj.get("information_ts"),
            "released_ts": obj.get("released_ts"),
            "links": LinksEntities.from_dict(obj["links"]) if obj.get("links") is not None else None
        })
        return _obj


