# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.1
  - indicators: 1.0.0
  - malware: 1.0.1
  - reports: 1.0.1
  - sources: 1.0.3
  - actors: 1.0.2
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.report_content import ReportContent
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class ReportResponseStream(BaseModel):
    """
    ReportResponseStream
    """ # noqa: E501
    breach_alert_count: StrictInt = Field(description="Number of breach alert reports")
    count: StrictInt = Field(description="Total number of reports")
    cursor_next: Optional[StrictStr] = Field(default=None, description="Stream position identifier to continue scrolling from")
    fintel_report_count: StrictInt = Field(description="Number of fintel reports")
    geopol_report_count: StrictInt = Field(description="Number of geopol reports")
    info_report_count: StrictInt = Field(description="Number of information reports")
    malware_report_count: StrictInt = Field(description="Number of malware reports")
    reports: Optional[List[ReportContent]] = Field(default=None, description="List of detailed reports")
    spot_report_count: StrictInt = Field(description="Number of spot reports")
    vulnerability_report_count: StrictInt = Field(description="Number of vulnerability reports")
    __properties: ClassVar[List[str]] = ["breach_alert_count", "count", "cursor_next", "fintel_report_count", "geopol_report_count", "info_report_count", "malware_report_count", "reports", "spot_report_count", "vulnerability_report_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportResponseStream from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reports (list)
        _items = []
        if self.reports:
            for _item_reports in self.reports:
                if _item_reports:
                    _items.append(_item_reports.to_dict())
            _dict['reports'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportResponseStream from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "breach_alert_count": obj.get("breach_alert_count"),
            "count": obj.get("count"),
            "cursor_next": obj.get("cursor_next"),
            "fintel_report_count": obj.get("fintel_report_count"),
            "geopol_report_count": obj.get("geopol_report_count"),
            "info_report_count": obj.get("info_report_count"),
            "malware_report_count": obj.get("malware_report_count"),
            "reports": [ReportContent.from_dict(_item) for _item in obj["reports"]] if obj.get("reports") is not None else None,
            "spot_report_count": obj.get("spot_report_count"),
            "vulnerability_report_count": obj.get("vulnerability_report_count")
        })
        return _obj


