# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0 (sha256: a6a51890d140b2280d6700ac6e108afa62dfb55bc79aa73b386946c7fa1e691f)
  - girs: 1.0.0 (sha256: f9f8228e2e27b95ba259939a46eda91618b96d6be76bbcba7db47dabb9515cdb)
  - indicators: 1.0.0 (sha256: 039a97ee798c2d28608d8b35f4eaa224b15c8a183a36cf2600321314f75f4777)
  - malware: 1.0.0 (sha256: 41c96d01c01cc5c93820e5dda691e8d0df53e28da1af8ccc84a233b29745fb11)
  - reports: 1.0.0 (sha256: 2050ae4d25813cd47834ae3843040a8d96723284b4b4ee4d2e4818a360a6aca7)
  - sources: 1.0.0 (sha256: a293621b477b279e532bde19e03f25becd2d7fb553b2b270d4e874ba206b823a)


    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from verity471.models.file import File
from typing import Optional, Set, TYPE_CHECKING
from typing_extensions import Self

if TYPE_CHECKING:
    # Only for type checkers; does not run at runtime.
    from verity471.verity_stix import STIXMapperSettings


class Template(BaseModel):
    """
    Template information
    """ # noqa: E501
    attachments: Optional[File] = Field(default=None, description="Attachments information.")
    body: Optional[StrictStr] = Field(default=None, description="Body of the template.")
    headers: Optional[StrictStr] = Field(default=None, description="Headers of the template.")
    raw_content: Optional[File] = Field(default=None, description="Raw content information.")
    sender: Optional[StrictStr] = Field(default=None, description="Sender of the template.")
    subject: Optional[StrictStr] = Field(default=None, description="Subject of the template.")
    __properties: ClassVar[List[str]] = ["attachments", "body", "headers", "raw_content", "sender", "subject"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_stix(self, settings: Optional["STIXMapperSettings"] = None):
        try:
            from verity471.verity_stix.mappers.common import StixMapper
        except ImportError as e:
            raise ImportError(
                "STIX support is an optional feature. "
                "Install with: pip install 'verity471[stix]'"
            ) from e
        stix_mapper = StixMapper(settings)
        return stix_mapper.map(self.to_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Template from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachments
        if self.attachments:
            _dict['attachments'] = self.attachments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of raw_content
        if self.raw_content:
            _dict['raw_content'] = self.raw_content.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Template from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attachments": File.from_dict(obj["attachments"]) if obj.get("attachments") is not None else None,
            "body": obj.get("body"),
            "headers": obj.get("headers"),
            "raw_content": File.from_dict(obj["raw_content"]) if obj.get("raw_content") is not None else None,
            "sender": obj.get("sender"),
            "subject": obj.get("subject")
        })
        return _obj


