# coding: utf-8

"""
    Verity471 Unified API

      - creds: 1.0.0
  - indicators: 1.0.0
  - malware: 1.0.0
  - reports: 1.0.0
  - sources: 1.0.1
  - actors: 1.0.0
  - watchers: 1.0.0
  - observables: 1.0.0
  - entities: 1.0.0
  - girs: 1.0.0


    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TranslationStatus(str, Enum):
    """
    Post translation status
    """

    """
    allowed enum values
    """
    WAITINGFORTRANSLATION = 'WaitingForTranslation'
    INPROGRESS = 'InProgress'
    DONE = 'Done'
    REJECTED = 'Rejected'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TranslationStatus from a JSON string"""
        return cls(json.loads(json_str))


